### ISSUE TITLE
Consider removing double underscores

### ISSUE THREAD

**Issue by badair** [gerritdaniels/ctrl#3]
> If you need to do some initialization after an object is deserialized, you can do this by adding a static __initialize member function to the class

It is my understanding that identifiers with two underscores are [reserved words](http://en.cppreference.com/w/cpp/keyword) in C++. From the link:

> all identifiers that contain a double underscore __ in any position and each identifier that begins with an underscore followed by an uppercase letter is always reserved (sic)

**Comment by gerritdaniels** [comment]
Is now implemented.
